// <auto-generated />
using System;
using DemandTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemandTrack.Api.Data.Migrations
{
    [DbContext(typeof(DemandContext))]
    partial class DemandContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DemandTrack.Api.Models.Demand", b =>
                {
                    b.Property<int>("TalepNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Açıklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Başlık")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Oluşturan_Kişi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Oluşturma_Tarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("TalepNo");

                    b.ToTable("Demands");
                });
#pragma warning restore 612, 618
        }
    }
}
